### ISSUE TITLE
Exception: org.openqa.selenium.UnhandledAlertException

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-core#1664]
Hello,

There is an issue with the following control verifyTextInDialog. It doesn't work on my side.
I get the issue below : 

The test case failed to be executed. More lickely due to an error in the test or in cerberus configuration. Exception: org.openqa.selenium.UnhandledAlertException: unexpected alert open: {Alert text : Commande arrondie à : 3. Confirmez vous ?} (Session info: chrome=64.0.3282.186) (Driver info: chromedriver=2.35.528139 (47ead77cb35ad2a9a83248b292151462a66cd881),platform=Linux 4.13.7-1.el7.elrepo.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information) Command duration o...

My control is : 
verifyTextInDialog    => "Commande arrondie à : 3. Confirmez vous ?"
So I expect an alert, but the execution fails and stops.
Is the right control to execute to verify the dialog content ?
You can also see the message displayed is too long :  
![image](https://user-images.githubusercontent.com/18569182/37960312-a478119c-31b5-11e8-8155-e81e052495cc.png)

No issue with the action manageDialog ok.

Selenium version : 3.10 node chrome

Thank you

Cerberus Version : 3.2-1296

**Comment by ryltar** [comment]
When an alert appears, by default, for selenium, it's not normal.
You can avoid this problem, by setting the following capability

**Comment by R-Loic** [comment]
Hello @ryltar ,

In my case, the alerts are expected, they are part of the functional process.
If I set the capability, i won't be able to verify their content or if they are well displayed.
