### ISSUE TITLE
Issue with drag and drop

### ISSUE THREAD

**Issue by R-Loic** [cerberustesting/cerberus-core#1745]
Hello,

It seems there is an issue with the cerberus drag and drop action (web application)
For the implementation, I use the following actions : 
MouseLeftButtonPress  =>  xpath=//div[contains(text(),'77 - Univ Badminton')]
MouseLeftButtonRelease  =>   xpath=//div[@class='md-card md-theme-ESS']

The actions are OK but nothing happen. Is the implementation good for a drag and drop ?
Do you meet the same issue ?

![image](https://user-images.githubusercontent.com/18569182/40913455-e7fa0a04-67f4-11e8-8e05-b8293bdd1971.png)

Selenium version 3.10
Chrome version 64
Cerberus 3.5

Could you have a look please ?
Thanks !

**Comment by ryltar** [comment]
Hello,

I just tried this on cerberus prod and we have the same issue.
I'm working on that !

**Comment by vertigo17** [comment]
linked to https://github.com/SeleniumHQ/selenium/issues/5429
new action using Javascript has been created in order to bypass.

**Comment by f3ltron** [comment]
hello can you give us some example ?

**Comment by vertigo17** [comment]
duplicate of https://github.com/cerberustesting/cerberus-core/issues/2036

**Comment by vertigo17** [comment]
Implemetation example using both Selenium and Sikuli.
https://qa.cerberus-testing.com/TestCaseScript.jsp?test=ENGINE%20:%20Action&testcase=0032B
