### ISSUE TITLE
implement ifElementPresent condition for FAT applications.

### ISSUE THREAD

**Issue by liquidparker** [cerberustesting/cerberus-core#1785]
Cerberus Version : 3.4-1335

Hello everybody,
I want include a condition in a step of an action like (see join)
![image](https://user-images.githubusercontent.com/40383408/42380306-b43b28b8-812d-11e8-9559-43af18aa72ec.png)
I want execute this action only if i see another picture in the screen.

Is it possible in Sikuli or not ?

Thanks for answer,
Regards, 
Julien S

**Comment by vertigo17** [comment]
in order to execute an action only if you see a picture in the screen you need to use IfElementPresent.
That condition only allow 1 parameter which is the picture that needs to appear in order for the action to trigger.

**Comment by liquidparker** [comment]
Hello Vertigo,

Thanks for Answer but i try ifElementPresent and it dont work (see join):
![image](https://user-images.githubusercontent.com/40383408/42449958-e04c04e8-8382-11e8-8bec-882c69a7eaa0.png)
Can you resolve this plz?

**Comment by liquidparker** [comment]
I forget to precise, its for system FAT (Sikuli), on Cerberus Version : 3.4-1335

**Comment by vertigo17** [comment]
Already fixed on previous version.
