### ISSUE TITLE
Implements Jax-RS

### ISSUE THREAD

**Issue by cDelage** [cerberustesting/cerberus-core#2034]
Jax-RS is Java API for RESTful Web Services,
Is standard for Java webservice creation.
Target is changed the servlet model to Webservices Rest model.
it will simplify developments to using it instead of servlet model.

To learn more about Jax-RS : http://spoonless.github.io/epsi-b3-javaee/javaee_web/jaxrs.html

**Comment by cDelage** [comment]
Jax-RS dependency have been added in this commit :
https://github.com/cerberustesting/cerberus-source/commit/6e4cac8e4435a8f080f5c0be3f760dda303a0f48

**Comment by vertigo17** [comment]
We will used Spring REST API in stead.
