### ISSUE TITLE
Drag and drop action

### ISSUE THREAD

**Issue by RobertoAbraul** [cerberustesting/cerberus-core#2036]
Hi,

it's possible to clarify if "drag and drop" action cannot be use in web?
Tried a simple test of drop and drag an element, using url: https://jqueryui.com/droppable/

![image](https://user-images.githubusercontent.com/14328346/68664889-fe3dec80-0538-11ea-8172-5c752308562c.png)

![image](https://user-images.githubusercontent.com/14328346/68664986-29284080-0539-11ea-9e0d-9e6b22ceaa4e.png)

Cerberus returns success, but the action is not done.

**Example using "drag and drop" action:** 
http://cerberus.siege.red/Cerberus/TestCaseScript.jsp?test=Cerberus%20Training&testcase=0002A
http://cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=85902963

Instead to make this action works we have to use "mouseLeftButtonPress" and "mouseLeftButtonRelease" actions.

**Example using "mouseLeftButton" actions:**
http://cerberus.siege.red/Cerberus/TestCaseExecution.jsp?executionId=85902854
http://cerberus.siege.red/Cerberus/TestCaseScript.jsp?test=Cerberus%20Training&testcase=0001A

Thanks.

**Comment by vertigo17** [comment]
It should work but current implementation is using a js function that may not work on all environments.
Maybe we should move to native selenium function.

**Comment by VanAlek6** [comment]
Interested about this point too because i'm unable to use it actually

**Comment by Kevin-Sinapayen** [comment]
Hi @vertigo17 

I have the same problem.
I have tried with mouse press/release, but it doesn't work either

![image](https://github.com/cerberustesting/cerberus-core/assets/139990094/4c24b34f-69c8-42f6-b805-8bd8c18e686b)

**Comment by vertigo17** [comment]
Execution in prod that fail :
https://prod.cerberus-testing.com/TestCaseExecution.jsp?executionId=595353

Same Test in QA:
https://qa.cerberus-testing.com/TestCaseScript.jsp?test=ENGINE%20:%20Action&testcase=0032B
If you execute it from QA it will succed.

Integrated in non regresion tests.
