### ISSUE TITLE
[Enhancement] Integration with Xray

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-core#2108]
Hello From Montreal !

I want to use both Xray (Jira plugin) and Cerberus

Xray intregrates well some automation tools like Cucumber or Robotframework

I would like to get the execution of the report of each Cerberus test to display on the corresponding test in Xray

Documentation Xray : 

https://confluence.xpand-it.com/display/public/XRAY/Integrating+with+Testing+Frameworks

Anyone here already use both of these tools together ?

Sincerly,

**Comment by glassalle59** [comment]
I found this documentation too
https://confluence.xpand-it.com/display/public/XRAY/Import+Execution+Results+-+REST

**Comment by vertigo17** [comment]
If I describe the use case:
For each Cerberus Campaign, I can link it to an XRay Test Plan
For each Cerberus Test Case, I can link it to an XRay Test.
Once this is done, when I start a Campaign execution on Cerberus side, it will acutomaticaly create the Test Execution on XRay side from the Test Plan. For every Test Case added to the campaign execution, Cerberus will add on XRay side the corresponding Test Execution attached to each Test.
 
I start to list here the dev to perform:
- [ ] Allow to edit from Test Case modal and link each Test Case with External referencial XRAY + Reference.
- [ ] Allow to edit on Campaign modal the XRAY Test Plan reference
- [ ] Allow to configure at Application level the necessary information to access JIRA : URL to access the Test, URL and credential endpoint (using a server side config file). 
- [ ] On Tag Creation, create the Test Execution on XRAY and save the ref to the tag.
- [ ] On each last retry execution update XRAY with corresponding result

Questions to answer:
If Cerberus create several execution per country, environnement and robot, should Cerberus still update the last execution submited (On XRay side there will be only 1 Test to update) ?

**Comment by vertigo17** [comment]
TODO:

- [ ] Fix status mapping for DC connectivity to: PASS, FAIL, EXECUTING, BLOCKED, ABORTED
- [ ] Enrish testEnvironments sections with list of env and countries

```
"testEnvironments": [
   "prod",
   "FR-Default"
]
```

**Comment by vertigo17** [comment]
A DC mapping issue was fixed with [commit](https://github.com/cerberustesting/cerberus-core/commit/bfcee3fa054238cbc0c247913f857ea7f8b7e6e0)

**Comment by MathisSenicourt** [comment]
New fixe with [commit](https://github.com/cerberustesting/cerberus-core/commit/52db6b1e97efc258ad8c5d352b4016a8e5658aa0)

**Comment by vertigo17** [comment]
fixed from release 4.17
