### ISSUE TITLE
Timezone management on (Campagn report over time)

### ISSUE THREAD

**Issue by MowglieRed** [cerberustesting/cerberus-core#2170]
Bonjour à vous, 

Nous avons constaté dans notre SI une anomalie dans l'affichage de l'heure de la campagne
![Time issue](https://user-images.githubusercontent.com/29864420/92404486-00121580-f134-11ea-83cc-91fc710d985b.png)
 dans cet exemple, la campagne a été lancée à 15H17 (Sep 7, 2020 8:00:49 AM) mais c'est 17H17 que l'on voit . : on voit un +2H sur l'heure de début d'exécution. 

Merci

**Comment by vertigo17** [comment]
Fixed on last version.
