### ISSUE TITLE
[Cerberus 4.13][Bug blocker][User management] - 404 Not Found

### ISSUE THREAD

**Issue by CLion59** [cerberustesting/cerberus-core#2296]
**Description**

On Cerberus 4.13, when I click on "Manage user", I'm redirected on 404 page.

**Comment by vertigo17** [comment]
Hello,
4.13 is not released yet.
Can you report the full version ? Is that Cerberus4.13-SNAPSHOT-1640 Build 20210910-132304 ?
What URL is redirected ? (the one that produce the 404)
Are you using Keycloak ?

**Comment by vertigo17** [comment]
I close the issue as I could not reproduce. Don’t hesitate to reopen or create a new one with the details if necessary.
