### ISSUE TITLE
can't open iOS application using bundleid

### ISSUE THREAD

**Issue by Minkyou-KIM** [cerberustesting/cerberus-core#2362]
Hi,
When I try to open iOS application using bundleid capability i am facing this issue:
...**'browserName' cannot be set together with 'bundleId' capability** 
even if I let empty browserName.

below the full cerberus's err msg:
The test case failed to be executed. More lickely due to an error in the test or in Cerberus configuration. The test case failed to be executed. Could not start Robot Server. org.openqa.selenium.SessionNotCreatedException: Unable to create a new remote session. Please check the server log for more details. 
Original error: An unknown server-side error occurred while processing the command. 
Original error: 'browserName' cannot be set together with 'bundleId' capability 
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03' System info: host: '1d130de86aad', ip: '172.17.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1062.12.1.el7.x86_64', java.version: '1.8.0_212' Driver info: driver.version: IOSDriver remote stacktrace: UnknownError: An unknown server-side error occurred while processing the command. Original error: 'browserName' cannot be set together with 'bundleId' capability at getResponseForW3CError (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/errors.js:804:9) at asyncHandler (/Applications/Appium.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:380:37) Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03' System info: host: '1d130de86aad', ip: '172.17.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1062.12.1.el7.x86_64', java.version: '1.8.0_212' Driver info: driver.version: IOSDriver.

**Comment by vertigo17** [comment]
Can you report the 'Robot Caps' json file from Robot tab on execution page to confirm the issue ?
It should contain **_RequestedCapabilities_** and _**FinalCapabilities**_.
Thanks

**Comment by vertigo17** [comment]
Hello Minkyou.
This is 'normal' as when browser is not defined, Cerberus default to firefox.
I will remove that rule in order to allow and leave it empty.
Are you able to test that change from qa.cerberus-testing.com environment (or are you able to test a snapshot release in order to test the fix) ?

**Comment by vertigo17** [comment]
Hello @Minkyou-KIM Were you able to test ?

**Comment by Minkyou-KIM** [comment]
Hi @vertigo17 it's good for us

**Comment by vertigo17** [comment]
Good. Thanks for the feedback
