### ISSUE TITLE
Implementation of Appium 'Set Context'

### ISSUE THREAD

**Issue by akatmiranda** [cerberustesting/cerberus-core#2408]
Hi!

We have an hybrid App and we constantly have to interact with Webviews. Actually there are elements in Webviews that we cannot read in our executions.
Is it possible to implement Appium 'Set Context' so we can change to Webview or Native in the middle of an execution?
As described here: [https://appium.io/docs/en/commands/context/set-context/](https://appium.io/docs/en/commands/context/set-context/)

Thanks!

**Comment by vertigo17** [comment]
The link provide a 404. Can you update it ?

**Comment by akatmiranda** [comment]
Hi!

Sure:
http://appium.io/docs/en/2.0/guides/context/
https://appium.readthedocs.io/en/latest/en/commands/context/set-context/

and a reference to the subject on lambdatest.com:
https://www.lambdatest.com/automation-testing-advisor/javascript/appium-driver.context

Thanks you.
