### ISSUE TITLE
[Bug] DragAndDrop action is not working

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-core#2420]
Hello,

When a test execute the action DragAndDrop, it is confused with the action Select, and an error occurs : Not executed because Action Select is not supported for application type IPA.

![81B7DADB-DDF0-405E-9698-6B73983984FC](https://user-images.githubusercontent.com/33724879/201655262-355f9dc5-1b88-4685-b769-dfcc07cd7b31.jpeg)

**Comment by vertigo17** [comment]
Issue in on error message.
This action is only supported for GUI and FAT applications.
Not yet supported for APK and IPA.
