### ISSUE TITLE
[LR] [User Experience] Execute a test deactivated on specific country

### ISSUE THREAD

**Issue by ittaLaRedoute** [cerberustesting/cerberus-core#2422]
Hello,

It could be good to prevent user to execute a test deactivated on specific country. 
For example, i deactivate my test for BE country in the execution settings:
![image](https://user-images.githubusercontent.com/97182913/201687875-be5ceb4a-be87-4558-9b34-bae54c699039.png)

I select BE country in run execution modal:
![image](https://user-images.githubusercontent.com/97182913/201688314-cd9e4489-9731-446c-8c94-647d415a0c5c.png)

When clicking on "Run", user is facing to a "processing" page without error message. It could be good to add a warning, a message to inform the user or prevent the user to launch the execution.
![image](https://user-images.githubusercontent.com/97182913/201694487-6bfbabbb-db93-48a5-8d3a-cc2033c780f3.png)

Moreover, this behaviour appears on some on our tests but with correct environments and country and we don't understand the problem.

Thanks.

**Comment by vertigo17** [comment]
Should be fixed with https://github.com/cerberustesting/cerberus-core/commit/b0a960843dbd05ce299f50ed33f7d8ad7376d546
Please confirm with latest snapshot

**Comment by ittaLaRedoute** [comment]
Hello, yes I can confirm it's OK,  I tried on Cerberus Redoute QA and the execution didn't launch.
