### ISSUE TITLE
KAFKA Parent Service Kafka Props don't work

### ISSUE THREAD

**Issue by jmlecul** [cerberustesting/cerberus-core#2425]
Cerberus Version : 4.15-1742

I have delete all kafka props from a kafka service (K002) and link with a parent service (K001) with identical kafka props
error appear : 
The test case failed to be executed. More lickely due to an error in the test or in Cerberus configuration. Could not start execution because failed when trying to retreive Kafka topics latest offsets on Service ARES_K002.QA - PRODUCT Topic search with adeokey and eventType V0.3. Failed to seek the Kafka topic 'adeo-dev-europe-west1-EVENT-SEQUOYA-REDWOOD-LM-ES-P1-C2-PRODUCT-V3' from server 'pkc-7yodp.europe-west1.gcp.confluent.cloud:9092'. org.apache.kafka.common.errors.TimeoutException: Timeout expired while fetching topic metadata 

i put the props back on the child service and it re work perfectly

***

i made a second try with only one props herited fail with same kind of error : 
Failed to call the Service 'ARES_K002.QA - PRODUCT Topic search with adeokey and eventType V0.3'. Caused by : Failed to search the Kafka topic 'adeo-dev-europe-west1-EVENT-SEQUOYA-REDWOOD-LM-ES-P1-C2-PRODUCT-V3' from host 'pkc-7yodp.europe-west1.gcp.confluent.cloud:9092'. org.apache.kafka.common.KafkaException: Failed to construct kafka consumer Caused by: org.apache.kafka.common.config.ConfigException: Use... (TOO LONG TO DISPLAY !! Please check Action, Control or Property detail).

seems parent props herited only work with REST API

**Comment by vertigo17** [comment]
Hello, Should be fixed.
Thanks for reporting.
