### ISSUE TITLE
Today date format : dd-mm-yyyy in Groovy

### ISSUE THREAD

**Issue by oljaillet** [cerberustesting/cerberus-core#2430]
Hello,

We just migrated Cerberus to 4.15 (buid 20221101-121513).
Java 1.8.0_212
MySQL 5.6.30

I have a very simple Groovy script that calculated today's date as dd-mm-yyyy

**new Date().format("dd-MM-yyyy")**

=> before that returned me the formatted date: 07-12-2022

=> Since now I have this message:

Groovy evaluation error: java.util.concurrent.ExecutionException: groovy.lang.MissingMethodException: No signature of method: java.util.Date.format() is applicable for argument types: (String) values: [dd-MM-yyyy]
Possible solutions: from(java.time.Instant), stream(), getAt(java.lang.String), parse(java.lang.String), print(... (TOO LONG TO DISPLAY !! Please check Action, Control or Property detail)

Does it seem to be missing imports? and if so, how to add them to our Cerberus install ?

Thank you

**Comment by vertigo17** [comment]
I add to include a dependency on pom file.
Latest snapshot has the fix included.

**Comment by oljaillet** [comment]
Bonjour Benoit, je ne suis pas très au fait du fonctionnement de github... 
Quelles actions sont a faire de notre coté pour avoir cette version corrigée sur notre environnement ?
Merci beaucoup

**Comment by vertigo17** [comment]
Vous avez installé Cerberus comment ?

Si c'est à partir d'un jar, tu peux utiliser ce lien :
https://vm.cerberus-testing.org/delivery/
Il y a toutes les images des dernières version mais surtout la version [cerberus-core-SNAPSHOT.war](https://vm.cerberus-testing.org/delivery/cerberus-core-SNAPSHOT.war)
qui est mise à jour automatiquement à chaque commit.

Si tu utilises les images docker tu peux utiliser la SNAPSHOT de https://hub.docker.com/r/cerberustesting/cerberus-as-tomcat/tags
Pareil, c'est mis à jour à chaque commit.
