### ISSUE TITLE
[Cerberus4.15-1742 Build 20221101-121513] [GL] Screenshots are not visible within IOS

### ISSUE THREAD

**Issue by Moujib-automate** [cerberustesting/cerberus-core#2439]
Hello, 
It's Moujib from GL, we have an issue with getting screenshots within IOS, for ANDROID it's working fine. 
This is an exemple of excution with systematic screenshots. 
![image](https://user-images.githubusercontent.com/124173930/216078930-1160b474-8d73-4b4c-ad46-6c6ebb9b4714.png)

We checked Cerberus logs and we have only this information
_Cerberus-4.15 - [Moujib Test - 0005A - step: 0 action: 7] Screenshot returned null._
I added the last two capabilities but still the same.
![image](https://user-images.githubusercontent.com/124173930/216078445-281d3cda-4fdd-4c93-aca6-0df307af5127.png)

**Comment by Moujib-automate** [comment]
Within Android we have some issues with screenshots as well , do you have an idea how to resolve the "screenshot is too big" issue 
![image](https://user-images.githubusercontent.com/124173930/216093878-eaf81f2b-b815-4eaf-abd9-ff169173a8bb.png)

**Comment by vertigo17** [comment]
you can change the parameter cerberus_screenshot_max_size in order to allow to save biger screenshot files.
I think it default to 1Meg but can easily be changed to 5048576

**Comment by Moujib-automate** [comment]
> you can change the parameter cerberus_screenshot_max_size in order to allow to save biger screenshot files. I think it default to 1Meg but can easily be changed to 5048576

Nice 👍  ! it worked fine for Android, however for IOS it's still the same , anyone facing the same issue with the same version ?

**Comment by Moujib-automate** [comment]
Hello , 
There is any news about that issue please , we are still blocked and we can't implement tests for IOS yet.

**Comment by vertigo17** [comment]
Hello. Are you able to replicate that issue using Browserstack ?

**Comment by Moujib-automate** [comment]
Hello , 
We switched to BrowserStack , the issue is not reproductible anymore.
Thank you for your help and assistance :)
