### ISSUE TITLE
Original error: socket hang up  / io.appium.uiautomator2.server

### ISSUE THREAD

**Issue by oljaillet** [cerberustesting/cerberus-core#2441]
Bonjour,

Je remarque que j'ai régulièrement l'erreur suivante lors de mes exécutions : 
Original error: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up

Pour régler le problème il suffit de relancer le device Android (mais ca nécessite de surveiller constamment ses exécutions !)

En faisant quelque recherche j'ai trouvé qu'il suffisait de forcer la fermeture de io.appium.uiautomator2.server (c'est plus rapide!).
adb -s <ad IP> shell am force-stop io.appium.uiautomator2.server

Y a t'il un moyen d'éviter cette erreur ou de lancer cette commande adb de façon automatiquement pour éviter ces déconnexions ?

Merci

**Comment by vertigo17** [comment]
Bonjour, 
Tu peux essayer de faire un step a la fin de tes case et d’y mettre une action executeCommand. 
en flagant le step en force execution, le step sera exécuté systématiquement même si une action ou contrôle arrete le test.

**Comment by oljaillet** [comment]
Merci Benoit, j'ai pas réussi, mais de toute façon je pense que mon approche n'est pas la bonne... 
je me dit que si j'arrivait a forcer l'arrêt de io.appium.uiautomator2.server pendant un test (même si c'est à la fin) du coup ca me planterait mon test et me le flaguerait à FA !

néanmoins pour le "step en force execution", je n'avait pas vu qu'il y avait cette option possible et dans certains de nos cas de test ca sera  super utile !! merci.
