### ISSUE TITLE
Pending SQL To be performed

### ISSUE THREAD

**Issue by hamedkhosrawi** [cerberustesting/cerberus-core#2443]
hello
i trying to install cerberus in docker, but after creating user in keycloak 2 issue appears for me, first after initialize databse, the process will stop for this reason "com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'cerberus.tag' doesn't exist", please inform me what i do
second after creating user in keycloak, in the log of cerberus container appears Duplicate entry 'meena' for key 'IX_user_01', what can i do for that,
thank you

**Comment by hamedkhosrawi** [comment]
hi
i checked again in logs and this error appears 
ERROR ReadMyUser:226 - org.cerberus.core.exception.CerberusException: Missing data.. null
org.cerberus.core.exception.CerberusException: Missing data.. null
I would be very grateful if you could guide me

**Comment by vertigo17** [comment]
That would be interesting to share what you did to solve the issue. 
Was that a bad mysql version ?

**Comment by hamedkhosrawi** [comment]
yes of course, i logged in to container then i edit the database.sql file in /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/ direcory , mysql was declaring statements containing the date 1970 as errors and then i commit the container as image and then  i try to restart the process Then the table(tag) was also created.
