### ISSUE TITLE
Groovy evaluation error: java.util.concurrent.ExecutionException: org.cerberus.core.service.groovy.impl.GroovyRestrictionException: Possible access of method plus on class ObjectRange is not allowed in Groovy transformations!

### ISSUE THREAD

**Issue by hamedkhosrawi** [cerberustesting/cerberus-core#2446]
hello
i tried execute some property from getFromGroovy, but each time i get this error 
`Groovy evaluation error: java.util.concurrent.ExecutionException: org.cerberus.core.service.groovy.impl.GroovyRestrictionException: Possible access of method plus on class ObjectRange is not allowed in Groovy transformations!`
could you help me?

**Comment by vertigo17** [comment]
Hello @hamedkhosrawi , can you provide a feedback on how you fixed this and what was the issue ?
Was that a groovy error ?
