### ISSUE TITLE
Chrome browser has a serious security vulnerability Pop up

### ISSUE THREAD

**Issue by AtomikPunch** [cerberustesting/cerberus-core#2447]
Hi, I'm actually trying to create a scenario on Cerberus using chrome.
One of my scenario is supposed to click on a burger menu on the header.
Unfortunately, the Chrome pop up tab is  placed right on my object, resulting on a failure.
but why can't you just click on the ignore button you may ask.
Well since my local chrome is updated, i'm not able to see nor track any objects on this pop up.
I wanted to ignore it but now i'm stuck and i have to deal with it.
On Cerberus i tried to choose different configuration with better versions of Chrome, but i get the same warning pop up.

![image](https://user-images.githubusercontent.com/116343689/222410984-2b18de9a-d133-4345-842b-731337dbb92e.png)

Is there any way i can deal with it ? Does someone has the html path to it ?

Thanks in advance.
  
Cerberus Version : 4.16-1747

**Comment by AtomikPunch** [comment]
Nevermind, i found the xpath of it using browser stack
Here's the path if anyone wants it.

![image](https://user-images.githubusercontent.com/116343689/222449627-7dfc8ccd-2928-4e56-92fe-e01c14485739.png)

**Comment by vertigo17** [comment]
I close at it seems to be fixed with the xpath.
I would suggest to clik on it with the condition that it is present.
I would also suggest to share this bahaviour with your dev team as I am not sure this is normal that this popup hide the burger menu.
