### ISSUE TITLE
Bug Modal edit service - Avro (key/value checkbox)

### ISSUE THREAD

**Issue by Cyril-Bellotti** [cerberustesting/cerberus-core#2448]
Cerberus Version : 4.16-1747

Hi,

This case was not present in 4.15. 

Key and value checkbox are not checked after save and refresh

How to reproduce ? 
1. Click on the button Edit service for a Kafka Service.
2. Click on the checkbox "key" and "value" to set it to true value
3. Save
4. If you refresh the page, and edit again you will see that the checkbox is set to false

Other case : 
1. Click on the button Edit service for a Kafka Service.
2. Click on the checkbox "key" and "value" to set it to true value
3. Save
4. Click on the button Edit service for an other Kafka Service that have checkbox set to false
5. You will see that the checkbox is set to true.
6. If you refresh again the page, all checkbox will be set to false.

![bug avro](https://user-images.githubusercontent.com/60349932/222446777-d0e840e8-3162-4c3d-991e-69bb909bada6.png)

**Comment by mflorid** [comment]
Can't reproduce it we can close

**Comment by MathisSenicourt** [comment]
@mflorid
 test
