### ISSUE TITLE
[LR][Bug][FFA] Regression - Cannot delete all property with the same name

### ISSUE THREAD

**Issue by ittaLaRedoute** [cerberustesting/cerberus-core#2454]
Hi,
On Cerberus version **4.16** and **4.17** we cannot delete all properties with the same name.
Clicking on the delete button for property name on the left nothing happens (the property are not set to be deleted):
![image](https://user-images.githubusercontent.com/97182913/224768409-079f60ab-58f5-4fe9-a972-e637338cf37e.png)
We have to click to delete one by one:
![image](https://user-images.githubusercontent.com/97182913/224768588-89b0a235-a24e-4ad4-bc87-02005081816a.png)
![image](https://user-images.githubusercontent.com/97182913/224768649-e55220a6-3c65-4720-a428-b875c0c61449.png)

**Comment by lucashimpens** [comment]
Issue is resolved
