### ISSUE TITLE
[Cerberus Version : 4.16-1747][GL] The command scroll to is not working

### ISSUE THREAD

**Issue by Moujib-automate** [cerberustesting/cerberus-core#2458]
Hello, 

we noticed that the command Scroll TO is not working ; it is performing a wait instead as shown in the screenshot

Cerberus Version : 4.16-1747
![image](https://user-images.githubusercontent.com/124173930/226958484-4806340b-e4b7-4b9a-be9f-bccb84820053.png)

**Comment by vertigo17** [comment]
I will need more detail and context on that.
Can you provide the page where you want to scroll and a screenshot of the element you want to scroll to.
That could be a wrong xpath or iframe issue.
Anyway you can always try to get around that issue by scrollTo using a text or using keyPress action with page down.

**Comment by mflorid** [comment]
We have the same issue here : #2450

**Comment by vertigo17** [comment]
Can you put the URL that you open and the xpath in text mode so that I try to reproduce ?
Thanks.

**Comment by mflorid** [comment]
> Can you put the URL that you open and the xpath in text mode so that I try to reproduce ? Thanks.

https://www.adeo.com/

xpath=(//*[@class="adeo-section fullwidth bg-darkblue padded"])[1]

or

text : À LA UNE

**Comment by vertigo17** [comment]
Issue should be fixed.
Don't hesite to reopen is not the case on latest master.

**Comment by MathisSenicourt** [comment]
Hi, the issue seems to be still present on 4.18

**Comment by MathisSenicourt** [comment]
The scroll doesn't work but there is no error from cerberus. To reproduce :

open url :
https://www.laredoute.it/ppdp/prod-350309180.aspx

reject cookies by cliking on:
//*[@id="popin_tc_privacy_button_2"]

scroll to :
//button[contains(@class,'product-rating-open-language')]//span


there is a bypass by using javascrip :

document.evaluate("XPATH HERE", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.scrollIntoView();

and example: document.evaluate("//*[@data-cerberus='color']", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.scrollIntoView();

**Comment by vertigo17** [comment]
fixed with commit https://github.com/cerberustesting/cerberus-core/commit/9757314baa56a5838d0bd830151027b319f980fb
