### ISSUE TITLE
[LR] Groovy script doesnt work

### ISSUE THREAD

**Issue by ittaLaRedoute** [cerberustesting/cerberus-core#2461]
Hello, i am struggling with a groovy scenario that doesnt want to run on Cerberus, even if it works on https://groovyconsole.appspot.com/

import java.text.* 
def start_time = new Date()
def sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
return sdf.format(start_time)​

How can i fix it ?

**Comment by oljaillet** [comment]
Hello, I had the same problem so I bypassed groovy and I used something like :  
%system.TODAY-dd%-%system.TODAY-MM%-%system.TODAY-yyyy%
