### ISSUE TITLE
[LR] UI test report not clear

### ISSUE THREAD

**Issue by ittaLaRedoute** [cerberustesting/cerberus-core#2463]
Hello, we notice that at the test execution report page, the background color has disappeared for a small round icon, less clear than before.
Can you change that ?
![image](https://user-images.githubusercontent.com/97182913/231097493-85b6eb99-50e3-4c03-970e-9c5fc65837ff.png)

another thing is that now when a step is not execute due to a boolean, we cant directly see the condition on the right, we have to focus on the tooltip, wich is not clear, can we add it also on the right part ?

Thans

**Comment by vertigo17** [comment]
I beleive everything has been pushed on that change right ?
If so, @lucashimpens, can you please close the issue ?
Thanks
