### ISSUE TITLE
Unable to give admin right to user

### ISSUE THREAD

**Issue by VanAlek6** [cerberustesting/cerberus-core#2467]
Hello,
I have full admin rights on my account but impossible to see the panel or delete what i'm creating (had no admin rights when account has been created).
I checked rights with another account and everything is ok. I tried to refresh, logout, and change languag but nothing work.
Is there an issue with that feature?

**Comment by vertigo17** [comment]
Are you using Keycloak ?
Maybe you have defined the right inside Cerberus when it should be done on Keycloak side.
Are you using a SaaS instance ?

**Comment by VanAlek6** [comment]
Hello, 
Sorry for the delay, i was waiting (vacations) for the one who created the environment...
As you said, it was a keycloak issue so everything is fine now. 
Thanks for the answer !
