### ISSUE TITLE
Passwords can be seen

### ISSUE THREAD

**Issue by Kevin-Sinapayen** [cerberustesting/cerberus-core#2469]
Hi,
Is it planned to have a new field type "password" to avoid displaying passwords in plain sight?
Thank you
Cerberus Version : 4.15-1742

**Comment by vertigo17** [comment]
You can already hide sensitive data either using:
1/ Any property that contain PASSW
2/ Any testdata that has been flagged as Encrypt
Any area that obviously contains secrets are automatically hidden with XXXXXX
If there are missing areas, please describe then and we will add them.

ex:
![image](https://github.com/cerberustesting/cerberus-core/assets/5342048/89597fbe-776f-4188-98ab-b6b15cbfb203)

**Comment by Kevin-Sinapayen** [comment]
Perfect thank you!
