### ISSUE TITLE
Some campaign can't be RUN or edited or deleted 

### ISSUE THREAD

**Issue by Moujib-automate** [cerberustesting/cerberus-core#2486]
Cerberus Version : 4.16-1747

Hello , 

Some of my campaigns with the following names can't be edited or run or modified : 

[TNR] SAPCC_WEB_DESKTOP_INT
TNR SAPCC_WEB_MOBILE_INT
TNR_SAPCC_WEB_MOBILE_INT
--

Behaviour in the vidéo : 
https://www.loom.com/share/7779a4df4ed44a7a843c5bb2a344ce6f

**Comment by vertigo17** [comment]
I can't reproduce on my side.
Are you able to reproduce the issue on our environment ?
idealy prod.cerberus-testing.com
Thanks.
