### ISSUE TITLE
Allow optional datalib's sub-data

### ISSUE THREAD

**Issue by abourdon** [cerberustesting/cerberus-core#2491]
Hello,

It should be great to allow optional sub-data if its corresponding mapped column/jsonpath is giving an error during the parse of the datalib's result set
This could be allowed by adding an "Optional" column in the sub-data table definition.

Regards
Aurélien

**Comment by bcivel** [comment]
Hello Aurélien,

The best is to return empty when a subdata is not retrieved during the parse of the resultset.

If the resultset is empty >> it should still return NA.
If the resultset is not empty, but one subdata is not retrieved (SQL column or path not in the result) >> Status become OK, and concerned subdata is empty.

Thanks for the help
Benoit
