### ISSUE TITLE
Impossible d'affecter une Build/Revision sur un environnement

### ISSUE THREAD

**Issue by InkUisitor** [cerberustesting/cerberus-core#2494]
**Contexte**

Cerberus 4.16 on premise (build custom juste pour faire tourner Selenium 4.X)

**Description**

A l'aide d'un compte administrateur, depuis l'interface "Intégration > Environnement", il m'est impossible de modifier les valeurs de Build / Revision à la création ou à la modification d'un environnement

**Reproduction**

Se connecter avec un compte administrateur
Disposer de données dans l'interface "Intégration > Définition des Versions"
Déplier le volet "Intégration", cliquer sur "Environnement"
Cas 1. Créer un nouvel environnement, sélectionner les informations obligatoires
Se positionner dans l'onglet "Build/Revision", constater que les champs sont modifiables mais tous vides
Cas 2. Editer un environnement existant.
Se positionner dans l'onglet "Build/Revision", constater que les champs ne sont même pas modifiables

**Comportement attendu**

Retrouver la liste des Build / Revision de l'interface "Intégration > Définition des versions" dans l'interface de création / édition d'environnement

**Contournement trouvé**

A l'aide de MySQL Workbench, il est possible d'affecter en direct les Build / Revision dans la table "cerberus.countryenvparam". Ainsi au déclenchement d'un test, il est possible de faire en sorte de prendre en considération les information de Build / Revision affectées à un test conformément à la configuration Build / Revision affecté à l'environnement

![opera_YSsgCzzfrU](https://github.com/cerberustesting/cerberus-core/assets/15886298/1754753c-eda7-480d-ba30-751e3574ea12)

**Comment by InkUisitor** [comment]
OK. Je viens de trouver le "contournemen" à l'aide du code pour faire en sorte de ne pas passer par la base de données mais par l'interface.
Pour ajouter une build à un environnement, il faut qu'il soit créé (l'affectation sur une création n'est pas fonctionnelle tout de même)
Une fois dans le tableau des environnements, il faut désactiver l'environnement depuis le bouton présent sur la ligne. Puis envoyer la notification depuis la nouvelle popup.
Activer à nouveau l'environnement fraichement désactivé et sélectionner la build / révision sur la nouvelle popup. Cliquer sur "Prévisualiser la notification" sinon le bouton "Activer et Envoyer la notification" reste désactiver, puis cliquer cette fois sur "Activer et Envoyer la notification"
Un petit gif pour mieux comprendre :
![opera_0at0RfmX1o](https://github.com/cerberustesting/cerberus-core/assets/15886298/d57996ca-8d0d-43e1-8fa2-a396d0af611e)

**Comment by vertigo17** [comment]
C'est effectivement le comportement attendu.
Un changement de build/revision se fait via l'interface graphique et/ou API.

https://qa.cerberus-testing.com/**DisableEnvironmentV000** permet de desactiver un environnement
https://qa.cerberus-testing.com/**NewBuildRevisionV000** permet de le basculer sur un nouveau build/rev.

La gestion de l'information Build/Rev sur un environnement ne peut pas etre fait directement. Il faut nécessairement un evenement de changement de version pour le mettre sur une nouvelle version. Dans un processus de déploiement / changement de version, il faut appeler Cerberus **DisableEnvironmentV000** au moment ou on commence le déploiement pour éviter que Cerberus lance les cas de test sur un env en cours de déploiement sans trop savoir si ca va fonctionner ou même sur quelle version on tourne.
Puis **NewBuildRevisionV000** quand le deploy est terminé et operationel (ca réactive l'env pour les tests en securisant qu'on teste bien la bonne version).

C'est donc pas un contournement mais la bonne manière de faire ;-).

PS1 : La creation d'un env, c'est le seul moment ou on peut directement mettre une version definie sans faire d'evenement. Ca permet de le créer en actif directement sur la bonne version.
PS2 : On peut enchainer directement une API NewBuildRevisionV000 sans passer par un disable. Ca permet de mettre à jour directement la bonne version.

Je ferme le ticket mais hésite pas à le rouvrir si tu souhaites échanger sur un potentiel changement de comportement.
