### ISSUE TITLE
[BUG] Can't create a property with too much characters

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-core#2497]
Cerberus4.17-SNAPSHOT

I am not able to create a property with a big number of character. Indeed, I want to variabilize the base64 text 

Example of the text I want to put in a property is on attachment
[TESTVARIABLE.txt](https://github.com/cerberustesting/cerberus-core/files/12858102/TESTVARIABLE.txt)

**Comment by vertigo17** [comment]
fixed by https://github.com/cerberustesting/cerberus-core/commit/f42d848f5e857f305c911daa850be3781ac29efa
datalib should be used to generate base64 file.
