### ISSUE TITLE
Unknow Selenium IDE command during selenium import

### ISSUE THREAD

**Issue by cencio91** [cerberustesting/cerberus-core#2498]
I'm using "import test case from Selenium IDE", but some instruction are not recognized.

Some examples are:

- Unknow Selenium IDE command 'waitForElementVisible' on target 'xpath=//nb-alert' with value '5000' - attesa che appaia il popup di errore
- Unknow Selenium IDE command 'assertText' on target 'css=.alert-message' with value 'Nome utente o password errati'

Is the 100% support of selenium IDE instruction in the roadmap?
It seems that these commands are skipped during execution. this is a problem since I can think that my test end correctly, but the test validation was skipped instead

Thank you

**Comment by vertigo17** [comment]
Can you provide the Selenium IDE script that you want to import as an example ?

**Comment by cencio91** [comment]
@vertigo17  Of course. I cannot share the original script, but I've created a minimal example that let you reproduce the error.
I'm sorry but I don't understan dhow to attach the file, so I had copied it inline

`
{
  "id": "9eda623d-2e58-4f15-a942-abff0eee3e77",
  "version": "2.0",
  "name": "prova",
  "url": "",
  "tests": [{
    "id": "69330a64-84d2-44c9-b7ac-a9e9e36e4879",
    "name": "Untitled",
    "commands": [{
      "id": "963f8465-bff3-4976-aee3-fb7db69e89f5",
      "comment": "",
      "command": "open",
      "target": "/",
      "targets": [],
      "value": ""
    }, {
      "id": "85e14921-216c-4e8b-b951-bc0a38e166a7",
      "comment": "",
      "command": "setWindowSize",
      "target": "2208x1014",
      "targets": [],
      "value": ""
    }, {
      "id": "b2ea7379-5ae8-4f59-9c08-37673c9a20aa",
      "comment": "",
      "command": "click",
      "target": "id=input-email",
      "targets": [
        ["id=input-email", "id"],
        ["name=username", "name"],
        ["css=#input-email", "css:finder"],
        ["xpath=//input[@id='input-email']", "xpath:attributes"],
        ["xpath=//input", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "9ad75672-8e96-4b33-bd5c-54fd2b454864",
      "comment": "",
      "command": "type",
      "target": "id=input-email",
      "targets": [
        ["id=input-email", "id"],
        ["name=username", "name"],
        ["css=#input-email", "css:finder"],
        ["xpath=//input[@id='input-email']", "xpath:attributes"],
        ["xpath=//input", "xpath:position"]
      ],
      "value": "admin@webagri.it"
    }, {
      "id": "54d0356c-832f-403c-8577-0094cf38d8a5",
      "comment": "",
      "command": "type",
      "target": "id=input-password",
      "targets": [
        ["id=input-password", "id"],
        ["name=password", "name"],
        ["css=#input-password", "css:finder"],
        ["xpath=//input[@id='input-password']", "xpath:attributes"],
        ["xpath=//div[3]/input", "xpath:position"]
      ],
      "value": "password_errata"
    }, {
      "id": "4f4b6f53-81c4-479f-9ad2-41536989f4ee",
      "comment": "",
      "command": "click",
      "target": "css=.appearance-filled",
      "targets": [
        ["css=.appearance-filled", "css:finder"],
        ["xpath=//button", "xpath:position"]
      ],
      "value": ""
    }, {
      "id": "3fb78831-8d79-417c-8ea6-3742be134c82",
      "comment": "attesa che appaia il popup di errore",
      "command": "waitForElementVisible",
      "target": "css=.status-basic",
      "targets": [
        ["css=.status-basic", "css:finder"],
        ["xpath=//nb-alert", "xpath:position"]
      ],
      "value": "5000"
    }, {
      "id": "d43755da-e7dd-4fca-bca8-42335c981ce5",
      "comment": "",
      "command": "assertText",
      "target": "css=.alert-message",
      "targets": [],
      "value": "Nome utente o password errati"
    }, {
      "id": "d5493ae7-9d48-4135-ad15-ddad2e5fb9ae",
      "comment": "",
      "command": "type",
      "target": "id=input-password",
      "targets": [
        ["id=input-password", "id"],
        ["name=password", "name"],
        ["css=#input-password", "css:finder"],
        ["xpath=//input[@id='input-password']", "xpath:attributes"],
        ["xpath=//div[3]/input", "xpath:position"]
      ],
      "value": "12345678"
    }, {
      "id": "8d5fc60d-4cee-48bc-91a5-87381b282956",
      "comment": "",
      "command": "click",
      "target": "css=.appearance-filled",
      "targets": [
        ["css=.appearance-filled", "css:finder"],
        ["xpath=//button", "xpath:position"]
      ],
      "value": ""
    }]
  }, {
    "id": "a02cf9a8-294b-47e1-970f-c66e0d4c8c94",
    "name": "error",
    "commands": [{
      "id": "0c0d80d5-ea49-45cf-89a2-75709f058e8f",
      "comment": "",
      "command": "open",
      "target": "https://www.google.it/",
      "targets": [],
      "value": ""
    }, {
      "id": "981a6132-ede6-4166-a3ec-4d804e964195",
      "comment": "",
      "command": "setWindowSize",
      "target": "1538x826",
      "targets": [],
      "value": ""
    }, {
      "id": "99f31abc-2d93-4c2e-add9-fea574538af3",
      "comment": "",
      "command": "verifyText",
      "target": "linkText=Immagini",
      "targets": [
        ["linkText=Immagini", "linkText"],
        ["css=.gb_F:nth-child(2) > .gb_E", "css:finder"],
        ["xpath=//a[contains(text(),'Immagini')]", "xpath:link"],
        ["xpath=//div[@id='gb']/div/div/div/div[2]/a", "xpath:idRelative"],
        ["xpath=//a[contains(@href, 'https://www.google.it/imghp?hl=it&ogbl')]", "xpath:href"],
        ["xpath=//div[2]/a", "xpath:position"],
        ["xpath=//a[contains(.,'Immagini')]", "xpath:innerText"]
      ],
      "value": "Immagini"
    }, {
      "id": "0d867f7a-a04b-47fa-b98c-53aff0a2ba40",
      "comment": "",
      "command": "waitForElementVisible",
      "target": "xpath=//img[@alt='Google']",
      "targets": [
        ["css=.lnXdpd", "css:finder"],
        ["xpath=//img[@alt='Google']", "xpath:img"],
        ["xpath=//div[5]/div[2]/div/img", "xpath:position"]
      ],
      "value": "5000"
    }, {
      "id": "ad29aee0-3beb-47fc-94f4-fa1a4717494d",
      "comment": "This one should give error, since the element is not present",
      "command": "verifyText",
      "target": "linkText=Text Not Present",
      "targets": [
        ["linkText=Immagini", "linkText"],
        ["css=.gb_F:nth-child(2) > .gb_E", "css:finder"],
        ["xpath=//a[contains(text(),'Immagini')]", "xpath:link"],
        ["xpath=//div[@id='gb']/div/div/div/div[2]/a", "xpath:idRelative"],
        ["xpath=//a[contains(@href, 'https://www.google.it/imghp?hl=it&ogbl')]", "xpath:href"],
        ["xpath=//div[2]/a", "xpath:position"],
        ["xpath=//a[contains(.,'Immagini')]", "xpath:innerText"]
      ],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "1450f833-4fff-4cf8-ad3f-b3fcea0a65d6",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": ["69330a64-84d2-44c9-b7ac-a9e9e36e4879"]
  }],
  "urls": ["https://vptracer.volentieripellenc.com/", "https://google.it/"],
  "plugins": []
}
`

Thank you

**Comment by cencio91** [comment]
@vertigo17  Of course. I cannot share the original script, but I've created a minimal example that let you reproduce the error.
I'm sorry but I don't understan dhow to attach the file, so I had copied it inline

`
{
  "id": "9eda623d-2e58-4f15-a942-abff0eee3e77",
  "version": "2.0",
  "name": "errore",
  "url": "",
  "tests": [{
    "id": "a02cf9a8-294b-47e1-970f-c66e0d4c8c94",
    "name": "error",
    "commands": [{
      "id": "0c0d80d5-ea49-45cf-89a2-75709f058e8f",
      "comment": "",
      "command": "open",
      "target": "https://www.google.it/",
      "targets": [],
      "value": ""
    }, {
      "id": "981a6132-ede6-4166-a3ec-4d804e964195",
      "comment": "",
      "command": "setWindowSize",
      "target": "1538x826",
      "targets": [],
      "value": ""
    }, {
      "id": "99f31abc-2d93-4c2e-add9-fea574538af3",
      "comment": "",
      "command": "verifyText",
      "target": "linkText=Immagini",
      "targets": [
        ["linkText=Immagini", "linkText"],
        ["css=.gb_F:nth-child(2) > .gb_E", "css:finder"],
        ["xpath=//a[contains(text(),'Immagini')]", "xpath:link"],
        ["xpath=//div[@id='gb']/div/div/div/div[2]/a", "xpath:idRelative"],
        ["xpath=//a[contains(@href, 'https://www.google.it/imghp?hl=it&ogbl')]", "xpath:href"],
        ["xpath=//div[2]/a", "xpath:position"],
        ["xpath=//a[contains(.,'Immagini')]", "xpath:innerText"]
      ],
      "value": "Immagini"
    }, {
      "id": "0d867f7a-a04b-47fa-b98c-53aff0a2ba40",
      "comment": "",
      "command": "waitForElementVisible",
      "target": "xpath=//img[@alt='Google']",
      "targets": [
        ["css=.lnXdpd", "css:finder"],
        ["xpath=//img[@alt='Google']", "xpath:img"],
        ["xpath=//div[5]/div[2]/div/img", "xpath:position"]
      ],
      "value": "5000"
    }, {
      "id": "ad29aee0-3beb-47fc-94f4-fa1a4717494d",
      "comment": "This one should give error, since the element is not present",
      "command": "verifyText",
      "target": "linkText=Text Not Present",
      "targets": [
        ["linkText=Immagini", "linkText"],
        ["css=.gb_F:nth-child(2) > .gb_E", "css:finder"],
        ["xpath=//a[contains(text(),'Immagini')]", "xpath:link"],
        ["xpath=//div[@id='gb']/div/div/div/div[2]/a", "xpath:idRelative"],
        ["xpath=//a[contains(@href, 'https://www.google.it/imghp?hl=it&ogbl')]", "xpath:href"],
        ["xpath=//div[2]/a", "xpath:position"],
        ["xpath=//a[contains(.,'Immagini')]", "xpath:innerText"]
      ],
      "value": ""
    }]
  }],
  "suites": [{
    "id": "1450f833-4fff-4cf8-ad3f-b3fcea0a65d6",
    "name": "Default Suite",
    "persistSession": false,
    "parallel": false,
    "timeout": 300,
    "tests": []
  }],
  "urls": ["https://google.it/"],
  "plugins": []
}
`

Thank you

**Comment by vertigo17** [comment]
I added the support for the 2 missing actions from your import file.
Here is the result.

![image](https://github.com/cerberustesting/cerberus-core/assets/5342048/82f4f3dc-b41b-4fb4-8627-a20d6235a50c)

Please open a new issue if you need more action mapping.

**Comment by cencio91** [comment]
Ok, thank you very much.
In general, I think it's more correct to trigger an execution error in case of unknown action
I wish you a nice day
