### ISSUE TITLE
Set variable of the browser

### ISSUE THREAD

**Issue by Kevin-Sinapayen** [cerberustesting/cerberus-core#2504]
Cerberus Version : 4.15-1742

Hi,

I need to set the _localStorage_ variable of the browser. I could not fond a solution in the documentation.

I tried with _execute JS command_ window.localStorage.setItem("isAutomatedTest", "true");

![image](https://github.com/cerberustesting/cerberus-core/assets/139990094/0f814a14-20bb-432b-aaa3-a42ef30fd50f)

**Comment by vertigo17** [comment]
This is for me the right way to do it.
Looks like you try to execute a js without opening a proper site. the browser URL starts by data: 
Did you try that after opening a correct website ?

**Comment by vertigo17** [comment]
Good.
