### ISSUE TITLE
[BUG] Cannot save test : ERROR - Request Entity Too Large

### ISSUE THREAD

**Issue by glassalle59** [cerberustesting/cerberus-core#2508]
Cerberus4.17-SNAPSHOT-1756 Build 20231015-163303 

Hello

When I save my test/ scenario, I have an error : **ERROR - Request Entity Too Large**

<img width="1739" alt="image" src="https://github.com/cerberustesting/cerberus-core/assets/33724879/9537c94c-18a6-41e4-a6af-0fece211afe7">

It seems that because I have many action "upload File to Robot" with a BIG content (Conversion from PDF to base64) in my scenario. Indeed, I need to upload 50 PDF on my test.

You can reproduce by adding one more time the last step on the scenario here : https://lmc.cerberus-testing.com/TestCaseScript.jsp?test=ECONTRAT%20-%20Sc%C3%A9narios&testcase=0004A&step=13&tabactive=tabSteps#

Is it possible to correct the error and allow me to upload many file in the same scenario ?

**Comment by vertigo17** [comment]
I beleive request is too big as it include all the files to upload. 
Maybe it can be fixed by increasing max size on application server side if possible. 
best will be to the manage files outside test case définition. If files are images you can already use it with .base64 suffix. 
for the other files we will have to create the screen and object.

**Comment by glassalle59** [comment]
all files I want to upload are PDF.
How can I manage these types of files outside test case ?

**Comment by vertigo17** [comment]
You can't yet.
Do you have any way to split your actions/controls on different testcases or reduce file sizes.

**Comment by glassalle59** [comment]
I resolve this issue by split the base64 value into many variables then concatenate the full value into a final variable with groovy

**Comment by vertigo17** [comment]
Good but Looks very dirty ;-(.

**Comment by vertigo17** [comment]
The error is coming from nginx http server.
As a workaround the following parameter can be changed (it default to 1M)

    client_max_body_size 5M;

inside config file 

    vi /etc/nginx/nginx.conf
;
Target to create data file object is still relevant though

**Comment by vertigo17** [comment]
fixed by https://github.com/cerberustesting/cerberus-core/commit/f42d848f5e857f305c911daa850be3781ac29efa
you can now use datalib FILE type and %datalib.DATALIBNAME.base64% variable inside testcase.
