### ISSUE TITLE
Robot froze

### ISSUE THREAD

**Issue by Kevin-Sinapayen** [cerberustesting/cerberus-core#2510]
Cerberus Version : 4.16-1747

Hi, I have the same issue https://github.com/cerberustesting/cerberus-core/issues/2505

![image](https://github.com/cerberustesting/cerberus-core/assets/139990094/36559b7a-99fb-46be-8ba7-6cd212f43080)

**Comment by vertigo17** [comment]
Fixed.
Linked with instability of mutualised robot infrastructure.

**Comment by Kevin-Sinapayen** [comment]
Thanks!
