### ISSUE TITLE
SaaS Cerberus access KO

### ISSUE THREAD

**Issue by Kevin-Sinapayen** [cerberustesting/cerberus-core#2511]
Cerberus Version : 4.16-1747

Hello,

We cannot access https://citeo.app.cerberus-testing.com/Homepage.jsp since a few minutes

![image](https://github.com/cerberustesting/cerberus-core/assets/139990094/8c364673-1fe7-40b2-8e0c-dcae2953787a)

**Comment by vertigo17** [comment]
This is now fixed.

**Comment by Kevin-Sinapayen** [comment]
Thank you @vertigo17
