### ISSUE TITLE
[Improvement] Add a property to have the number of rows in a data librairy

### ISSUE THREAD

**Issue by Michael-Eqiom** [cerberustesting/cerberus-core#2516]
When you insert data in a data library with sql for exemple, the number of inserted rows is displayed in Cerberus interface but not usable.
This info can be useful for control/loop

**Comment by vertigo17** [comment]
From this commit you can now use %property.PROP.nbrows%

**Comment by Michael-Eqiom** [comment]
[like]  Nentwig, Michael reacted to your message:
________________________________
