### ISSUE TITLE
Improvement - Campaign Report Collapsed by default when loading a campaign

### ISSUE THREAD

**Issue by ittaLaRedoute** [cerberustesting/cerberus-core#2523]
Hello, 

I have an improvement to suggest concerning the reports on the campaign pages, all the reports should be collapsed by default, instead of having some opening for no apparent reason

To see this issue:
* Go to "Campaign Execution Report"
* Search for “APP_TEST_CAMPAIGN_20240318-131718”
* Click on “Load”
* Scroll down
* We notice that the report [Report By Application Environment Country RobotDecli] is open by default

![imagem](https://github.com/cerberustesting/cerberus-core/assets/97182913/2ed228d4-1975-43d4-a386-6ff3794d348f)

Thank you for your consideration,

Cláudio B.

**Comment by vertigo17** [comment]
The curent rule is that if the content is not too big (< 10 lines) it opens by default.

**Comment by vertigo17** [comment]
fixed on latest version.
All agregations report panel are hidden by default and can be shown with selectbox.
That makes indeed screen ligher.

![image](https://github.com/cerberustesting/cerberus-core/assets/5342048/bee29a4b-8567-445d-956b-696ae1d14f8c)
