### ISSUE TITLE
Execution times 2hours gap

### ISSUE THREAD

**Issue by MathisSenicourt** [cerberustesting/cerberus-core#2526]
There is a strange behavior on execution times.
Campaigns that take 14 seconds or less to execute have a duration time of 120 minutes on tag information.

![image](https://github.com/cerberustesting/cerberus-core/assets/73992182/38232060-69a7-4919-b106-150542601d82)

Somehow it seems that we have different hours on executions on the same campaign:

![image](https://github.com/cerberustesting/cerberus-core/assets/73992182/1ee03a34-d6b0-4623-9f2e-c92f16faade0)
(table testcasestepexecution)

As you can see we have a difference of 2 hours on the same campaign.

![image](https://github.com/cerberustesting/cerberus-core/assets/73992182/c22f5514-32bf-4c12-8f3d-a98cddcd3761)

**Comment by vertigo17** [comment]
Can you share the result of SQL:

select id, Start, End, DateCreated , DateModif  from cerberus.testcaseexecution order by id desc;

by filtering around the timing where  those things happen.

Can you check 
1/ the timezone of the application server (tomacat) ?
2/ the timezone of the database server ?

FYI, start and end are coming from Application server.
DateCreated and DateModif are set from database.

Thanks
