### ISSUE TITLE
Error while creating new environment on applications page

### ISSUE THREAD

**Issue by j0hnsa** [cerberustesting/cerberus-core#2530]
When trying to create new environments on a application the following error is being displayed:
![image](https://github.com/user-attachments/assets/07e86365-773f-4995-a871-85dbea5e55b1)

Cerberus4.18-1783 Build 20240702-141356

**Comment by vertigo17** [comment]
Hello @j0hnsa this issue is already fixed on snapshot. 
if you don’t want to deploy snapshot, can you try to create them from integration/environment menu ? Not sure if this works.
