### ISSUE TITLE
[ROBOT page] PRD - BUG wrong value for executor proxy type

### ISSUE THREAD

**Issue by ittaLaRedoute** [cerberustesting/cerberus-core#2540]
When we load the robot details for the first time, if that robot has a proxy defined (for example ODIN_CHROME_EXECUTOR), most of the time the correct value will not appear on “Proxy Type“ field. It is NONE or even empty (depending on the browser):

![image](https://github.com/user-attachments/assets/1d16ba8c-550e-49f0-af05-1e430529c0bc)

**If we save the robot in this condition, it will update the field executorProxyType on table  robotexecutor with the NONE or empty.** 

To have the correct value, we have to close and reopen the robot. Them all the fields are correctly loaded:

![image](https://github.com/user-attachments/assets/b9d05483-510e-4340-805b-69dcf8f117f5)

**Note** : We suspect this is due to the components loading when the page is loaded. This is applicable for any robot and reproduces in PROD.

**Comment by MathisSenicourt** [comment]
@ittaLaRedoute FIXED 👍
