### ISSUE TITLE
[BUG] Cannot create Datalibrary with CSV

### ISSUE THREAD

**Issue by cencio91** [cerberustesting/cerberus-core#2543]
Hi,

I'm trying to create a CSV data library, but CSV is not readden

Step to reproduce:

1. I've uploaded a CSV contains the following :
```
ADMIN_USER,ADMIN_PASSWORD
myuser,mypass
```

2. Then i've checked the flag "Generate Subdata list from First line of csv after saving
(only when checked and with file uploaded)" ,selected **type=FILE-CSV**, a country and a System (blank environment).

3. when I click on "SAVE", the page infinite loads with this image:
![immagine](https://github.com/user-attachments/assets/ef0dd724-c419-4bb2-a8eb-35bf4f9b0174)

4. If i force reload, I can see the newly created datalibrary, but the SubData are not filled, and the download button shows **"Object not found !!"**

![immagine](https://github.com/user-attachments/assets/89c52408-266f-441d-894e-3400d91393e8)

5. Also if I add the SUBDATA manually, I get an error (**cerberus key subdata has no csv column position mapped...**) during execution. This is a minimal test configuration:
![immagine](https://github.com/user-attachments/assets/08d1ff02-14fe-4e3b-b45d-7f18fa5787e4)
![immagine](https://github.com/user-attachments/assets/12629f1d-b346-4f9e-880a-bdcb3ee0047c)
![immagine](https://github.com/user-attachments/assets/6f1efd95-7a5a-46eb-996d-9b583f033022)

Consideration:
- If i use "INTERNAL" as data library type, the same code works.
- if i create the datalibrary as CSV --> manually create a row in SUBDATA --> save it without marking "Generate Subdata list from First line of csv after saving" --> then reopening the data library, reupload the CSV and mark "Generate Subdata list from First line of csv after saving", it works.
**I think that the generation of the first blank row in SUBDATA is missing during the automated fill.**

Cerberus Version : 4.19-SNAPSHOT-1858, inside a docker container and MySQL v8

P.S: I've tryed both setting the delimiter to ',' than leaving it blank. I've tryed also with older version of snapshot (about 2 month ago)

thank you very much,
Francesco

**Comment by vertigo17** [comment]
Fixed with https://github.com/cerberustesting/cerberus-core/commit/75b90cee2b5b19497ac1a69ec42501c8a387c257
