### ISSUE TITLE
[BUG] - Cannot add application to environment

### ISSUE THREAD

**Issue by ittaLaRedoute** [cerberustesting/cerberus-core#2544]
Hello,

On Environment.jsp page, when adding an application to an environment we get the error: 

![image](https://github.com/user-attachments/assets/c121920f-02d0-4019-a5db-b4b4d4ffb5e4)

On the first attempt all systems were selected, but same behaviour if we only select the correct system (so maybe not related to the system).

Nonetheless, we can add the application to the environment on the application page.

Version: Cerberus4.19-SNAPSHOT-1813 Build 20240726-142532

Also, we did a test on https://qa.cerberus-testing.com/ we can't reproduce our issue but another issue is present : modal get stuck on Processing

![image](https://github.com/user-attachments/assets/3da987f2-975d-416a-98fd-25fff8e68760)

**Comment by lucashimpens** [comment]
After deploy the new version on our QUA environment, I confirm the modal now stucks on "Processing".
Extract of logs just after clicking on Save Button: 
![image](https://github.com/user-attachments/assets/d9393f32-ebbb-4c94-a47f-12a1c96b6d94)

**Comment by lucashimpens** [comment]
Hello Benoit,
Thank you for the fast actions
The issue about modal stucking is now fixed, but we have again the SQL Exception we had at the first time, so I reopened it :)
