### ISSUE TITLE
[BUG] - ReportingExecutionByTag.jsp page stays on loading

### ISSUE THREAD

**Issue by ittaLaRedoute** [cerberustesting/cerberus-core#2545]
Hello,

In our Cerberus QUA, sometimes the ReportingExecutionByTag.jsp stays loading:

![image](https://github.com/user-attachments/assets/c82b1efc-2866-431e-94dd-e1f062860ce6)

It seems that the End field on table testcaseexecution is null (for example when connection to Selenium fails) and it returns a Java exception.
It also impact the Execution List page: no executions are loaded on the page and error 500 on ReadTestCaseExecution servlet.

![image](https://github.com/user-attachments/assets/bf1da27e-02fa-4b23-99cd-2715516c06f2)

Extract of Testcaseexecution table:
![image](https://github.com/user-attachments/assets/34ef4e30-7efd-4de7-9a53-4313494d91d3)

We noticed that there were some changes on database, date field can now have NULL values:
![image](https://github.com/user-attachments/assets/bd9a4d42-a084-4eb0-bc61-d00623744ee9)

Version: Cerberus4.19-SNAPSHOT-1813 Build 20240726-142532

This is blocking for us to deploy a new release on production.

**Comment by vertigo17** [comment]
Thanks for the precise report. That should be fixed.
