### ISSUE TITLE
[BUG][Service REST]After an update database tables appservicecontent and appserviceheader are emptied

### ISSUE THREAD

**Issue by ittaLaRedoute** [cerberustesting/cerberus-core#2554]
Hello,
We have a blocking issue for the planned release of version 4.19 snapshot-1873

Steps to reproduce:
1) create a REST service with body type=raw and with some Headers and a parameters
2) Update the service path from test case script and save

![image](https://github.com/user-attachments/assets/97a61b47-2b8e-4a33-b854-70816ac99df2)

3) Do an update and save several times until you get an error:

![image](https://github.com/user-attachments/assets/12b7886f-adf6-4790-bd71-88a550fb6c48)

Expected result:
Service saved with the update

Current result:
- Error message
- Service not saved
- database tables appservicecontent completely emptied and appserviceheader left with only 2 lines.

Can you please help?
Thank you

**Comment by vertigo17** [comment]
Hello.
I could not reproduce the issue. 
I updated the service 10 times without never having the service name empty neither having any error.
I added a control in order to prevend the service name to be empty.
That will avoid the massive impact of empty those tables returning an error message on service name that cannot be empty..

**Comment by ittaLaRedoute** [comment]
Hello,
After many tests I found steps to reproduce the issue almost systematically
1) Create a REST service with type=raw + a path + headers + simulation parameters (I'm not sure all these details matter but did not test without them)
2) Call the service from a test case and save
3) Update service from test case:
![image](https://github.com/user-attachments/assets/e55bab63-429f-4cc1-a81b-7e5e0d03a5db)
4) Save service
5) Save test case
6) Update service from test case again:
![image](https://github.com/user-attachments/assets/22b4c008-ba27-46dd-abbf-c767c71f0f35)
7) here you should notice that service name is empty and by saving the service tables appservicecontent and appserviceheader are emptied.

Can you please help analyse why service name is emptied?
Thank you

**Comment by vertigo17** [comment]
I still did not manage to reproduce but found a case that when you change service name (from a callService Action inside testcase script page) to a service that do not exist, the Add button do not appear correctly.
Pressing that button could cause the modal to load with an empty value on service name.
Both were fixed.
I let you confirm that this is fine on your side.

**Comment by ittaLaRedoute** [comment]
Hello,
We do not have the button Add:
![image](https://github.com/user-attachments/assets/59d5081b-1d2b-46be-8ded-4f704d1fe82a)

**Comment by vertigo17** [comment]
Strange that the + (plus) Button does not appear. It should when service does not exist.
Can you reproduce from qa.cerberus-testing.com ?

**Comment by ittaLaRedoute** [comment]
Hello, 
No, I do not reproduce on 
But sometimes when I type quickly, 2 or 3 "+" buttons appear
![image](https://github.com/user-attachments/assets/5e9b7e7d-a0a0-42c5-ba32-f919083e3df3)
