### ISSUE TITLE
Change the actions done for the instruction : "Select"

### ISSUE THREAD

**Issue by MichaelWil** [cerberustesting/cerberus-core#558]
Hi,

Currently 2 instructions exist on Cerberus : "Select" and "click". On the Redoute website when you are on the pdp of a multisku product you have to select (for instance) the size.
The actions that are really done are : 
1- you click on the drop box
2- you click to select a size.

The action that are done by Selenium is : 
- select directly a size.

So currently it works but as the behavior are not the same the results may be different too.
And it happens in the following case : we had a bug on the mobile where a css prevent the "normal" user to click on the drop down menu so it was a bug.
But as Cerberus use the instruction "select" it worked and the bug can't be seen which is quite strabge for a non regression tool.

So the idea will be to change the actions done behind a "select" instead of doing a select it'll be better to do 2 clicks.

Thanks to update.

Michael

**Comment by vertigo17** [comment]
For me both actions should be kept.
Either you shortcup the combo select by using select, either you strictly want to do what the user do with the 2 clicks
